### ISSUE TITLE
Profile for Loupedeck

### ISSUE THREAD

**Issue by Ninovui** [neilenns/streamdeck-trackaudio#228]
Hello !
I'd like to know if this plugin can be adapted for Loupedeck users ?
I can't use it since I bought (and sometimes I regret it) a Razer Streamdeck, which runs on loupedeck.

Is it possible ?

Thanks !

**Comment by neilenns** [comment]
Unfortunately no, this was written specifically for Elgato streamdecks. I don't even have a Razer/Loupedeck.

**Comment by Ninovui** [comment]
Thank you for you kind reply,
However, it would be nice, considering there are some concurrent in the steamdeck industry… an adaptation isn’t really possible ? Thanks

**Comment by neilenns** [comment]
It isn't possible for me to do.
