### ISSUE TITLE
Show active station automatically? 

### ISSUE THREAD

**Issue by sk0941** [neilenns/streamdeck-trackaudio#257]
Is there any way to make it so that it shows your active stations automatically on the stream deck? As it is now, it's great if you're controlling the same positions, but if you're jumping between different positions/FIR's it becomes a bit of a hassle to type in all the call signs and such.

Maybe say you have 3 tiles set to show stations, and they would be populated by the top 3 stations from TrackAudio, depending on your call sign?

**Comment by neilenns** [comment]
I don't think so unfortunately, I can't create actions on the fly in StreamDeck. I tried to do it the other way around, where the StreamDeck buttons would auto-add themselves as stations in the correct state in TrackAudio automatically but for a variety of reasons it wasn't possible.

What I do is set up different StreamDeck profiles for my different positions. I have, for example, SEA_TWR, PDX_TWR, etc. then I just switch to the correct profile for the position I'm working.

**Comment by sk0941** [comment]
Hmmm bummer, but oh well. Something else that might be doable then, have the gain bound to one of the rotary knobs on the StreamDeck+?

**Comment by neilenns** [comment]
> Hmmm bummer, but oh well.

The multiple profile thing works well. You can copy/paste the buttons across the profile then just tweak the position name. I have a pretty standard setup for each airport that does DEL/GND/TWR/APP/CTR.

> Something else that might be doable then, have the gain bound to one of the rotary knobs on the StreamDeck+?

That'd be doable in the long run with a few tweaks to TrackAudio but I don't have a StreamDeck+ to test with 🥲
