### ISSUE TITLE
Add StreamDeck action to allow PTT

### ISSUE THREAD

**Issue by aselder** [neilenns/streamdeck-trackaudio#60]
Allow a StreamDeck key to act as a PTT for TrackAudio.

There isn't a websocket endpoint for this yet, but Pierre says it will be easy for him to add.

**Comment by neilenns** [comment]
This can be done already using [vjoy](https://www.bing.com/search?pglt=673&q=streamdeck+vjoy&cvid=951922ed00c544db826cce99e5cce87a&gs_lcrp=EgZjaHJvbWUyBggAEEUYOdIBCDQ1MzRqMGoxqAIAsAIA&FORM=ANNTA1&adppc=reversed&PC=DCTS) or [SuperMacro Keystroke PTT](https://docs.barraider.com/faqs/supermacro/getting-started/).

**Comment by neilenns** [comment]
Pierre may have convinced me to do this anyway 😅

**Comment by aselder** [comment]
Neither of those solutions support Mac OS X. 

Apparently apps like StreamDeck and Logitech G HUB, when emitting key presses don't use standard OS X events.

Using Karabiner-EventViewer, when I tap D on my laptop keyboard, I see a KeyDown and KeyUp event. When I have a StreamDeck key set to a hotkey of D and hit it, I don't see any events in Karabiner-EventViewer event though a D will show up in my document.

This means that a StreamDeck HotKey can't be used as a keypress to trigger TrackAudio PTT. Similarly, StreamDeck HotKeys can't trigger Discord keybinds.

**Comment by aselder** [comment]
I'm happy to help out with the code to do this, just need to sharpen my TS skills.

**Comment by neilenns** [comment]
It's fine, Pierre laughed at me in Discord.

It won't be hard to do but will come after the basic tx/rx/xc toggling is in place, and that's pending a massive PR on the trackaudio side that is pending some troubleshooting elsewhere.

**Comment by neilenns** [comment]
Will do after https://github.com/neilenns/streamdeck-trackaudio/issues/23 is complete.

**Comment by neilenns** [comment]
This is working but depends on changes on the TrackAudio side (https://github.com/pierr3/TrackAudio/issues/52)

**Comment by neilenns** [comment]
Uhhh somehow this code got lost. WTF.

**Comment by neilenns** [comment]
@aselder This is fully supported now using TrackAudio 1.3.0-beta-1 and v2 of the plugin.
